
package blackjackvinteum.view;//

import javax.swing.ImageIcon;
import blackjackvinteum.players.Cards;
import blackjackvinteum.players.Dealer;
import blackjackvinteum.players.Player;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor da Silva Rodrigues
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private final String NULL_CARD_PATH = "/cards/imagens/back.png";
    private Integer round = 0;
    private Player jogador;
    private Dealer dealer;
    private Cards CartaAtualPlayer;
    private Cards CartaAtualDealer;
    private final int STACK_INDEX = 0;
    private int playerIndexCounter = STACK_INDEX; //indice da pilha invertida. 0 == topo, 1 == segunda casa, etc...
    private int dealerIndexCounter = STACK_INDEX;
    
    public void novoRound(){
            round++;
            dealer = new Dealer();
            jogador = new Player();
            DealerHandIcon.setIcon(createImageIcon(NULL_CARD_PATH));
            PlayerHandIcon.setIcon(createImageIcon(NULL_CARD_PATH));
            jLabelDealerCount.setText("0");
            jLabelPlayerCount.setText("0");
            CartaAtualDealer = dealer.bet();
            dealerIndexCounter = STACK_INDEX;
            DealerHandIcon.setIcon(createImageIcon(CartaAtualDealer.getIconPath()));
            jLabelDealerCount.setText(dealer.getHandTotal().toString());        
    }
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {                                       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DealerHand = new javax.swing.JPanel();
        DealerHandIcon = new javax.swing.JLabel();
        PlayerHand = new javax.swing.JPanel();
        PlayerHandIcon = new javax.swing.JLabel();
        jLabelDealerTotal = new javax.swing.JLabel();
        jLabelDealerCount = new javax.swing.JLabel();
        jLabelPlayerTotal = new javax.swing.JLabel();
        jLabelPlayerCount = new javax.swing.JLabel();
        jButtonStand = new javax.swing.JButton();
        jButtonHit = new javax.swing.JButton();
        jButtonDealerHandLeft = new javax.swing.JButton();
        jButtonDealerHandRight = new javax.swing.JButton();
        jButtonPlayerHandLeft = new javax.swing.JButton();
        jButtonPlayerHandRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJack Vinte e Um");
        setResizable(false);

        DealerHand.setBackground(new java.awt.Color(214, 217, 223));
        DealerHand.setMaximumSize(new java.awt.Dimension(235, 334));
        DealerHand.setMinimumSize(new java.awt.Dimension(234, 333));
        DealerHand.setPreferredSize(new java.awt.Dimension(179, 250));

        DealerHandIcon.setMaximumSize(new java.awt.Dimension(235, 334));
        DealerHandIcon.setMinimumSize(new java.awt.Dimension(234, 333));

        javax.swing.GroupLayout DealerHandLayout = new javax.swing.GroupLayout(DealerHand);
        DealerHand.setLayout(DealerHandLayout);
        DealerHandLayout.setHorizontalGroup(
            DealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DealerHandIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DealerHandLayout.setVerticalGroup(
            DealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DealerHandIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PlayerHand.setBackground(new java.awt.Color(214, 217, 223));
        PlayerHand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        PlayerHand.setToolTipText("");
        PlayerHand.setMaximumSize(new java.awt.Dimension(235, 334));
        PlayerHand.setMinimumSize(new java.awt.Dimension(234, 333));
        PlayerHand.setPreferredSize(new java.awt.Dimension(235, 334));

        PlayerHandIcon.setForeground(new java.awt.Color(0, 0, 0));
        PlayerHandIcon.setMaximumSize(new java.awt.Dimension(235, 334));
        PlayerHandIcon.setMinimumSize(new java.awt.Dimension(234, 333));
        PlayerHandIcon.setPreferredSize(new java.awt.Dimension(234, 333));

        javax.swing.GroupLayout PlayerHandLayout = new javax.swing.GroupLayout(PlayerHand);
        PlayerHand.setLayout(PlayerHandLayout);
        PlayerHandLayout.setHorizontalGroup(
            PlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayerHandIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 233, Short.MAX_VALUE)
        );
        PlayerHandLayout.setVerticalGroup(
            PlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayerHandIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 332, Short.MAX_VALUE)
        );

        jLabelDealerTotal.setText("DEALER_TOTAL:");

        jLabelDealerCount.setText("0");

        jLabelPlayerTotal.setText("PLAYER_TOTAL:");

        jLabelPlayerCount.setText("0");

        jButtonStand.setText("Stand");
        jButtonStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerStandPerformed(evt);
            }
        });

        jButtonHit.setText("Hit");
        jButtonHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerHitPerformed(evt);
            }
        });

        jButtonDealerHandLeft.setText("<");
        jButtonDealerHandLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDealerHandLeftActionPerformed(evt);
            }
        });

        jButtonDealerHandRight.setText(">");
        jButtonDealerHandRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDealerHandRightActionPerformed(evt);
            }
        });

        jButtonPlayerHandLeft.setText("<");
        jButtonPlayerHandLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayerHandLeftActionPerformed(evt);
            }
        });

        jButtonPlayerHandRight.setText(">");
        jButtonPlayerHandRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayerHandRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDealerHandLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDealerHandRight))
                    .addComponent(jButtonStand)
                    .addComponent(jButtonHit)
                    .addComponent(DealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPlayerTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPlayerCount))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDealerTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDealerCount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPlayerHandLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlayerHandRight)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDealerTotal)
                        .addComponent(jLabelDealerCount))
                    .addComponent(DealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDealerHandLeft)
                    .addComponent(jButtonDealerHandRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonHit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayerTotal)
                    .addComponent(jLabelPlayerCount)
                    .addComponent(jButtonStand))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlayerHandLeft)
                    .addComponent(jButtonPlayerHandRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerHitPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerHitPerformed
        if (jogador.getHandTotal() < 17){
            CartaAtualPlayer = dealer.deal();
            
            if (CartaAtualPlayer != null){
                PlayerHandIcon.setIcon(createImageIcon(CartaAtualPlayer.getIconPath()));
                jogador.addHand(CartaAtualPlayer);
                playerIndexCounter = STACK_INDEX;
            }
            
            jLabelPlayerCount.setText(jogador.getHandTotal().toString());
            
            if (jogador.getHandTotal() > 21){
                JOptionPane.showMessageDialog(null, "Você Perdeu :( ", "Game Over", JOptionPane.ERROR_MESSAGE);
                novoRound();
            }else{
                if (!dealer.isStanding()){
                    CartaAtualDealer = dealer.bet();
                    jLabelDealerCount.setText(dealer.getHandTotal().toString());
                    
                    if (CartaAtualDealer != null){
                        DealerHandIcon.setIcon(createImageIcon(CartaAtualDealer.getIconPath()));
                        dealerIndexCounter = STACK_INDEX;
                    }
                    if (dealer.getHandTotal() > 21){
                        JOptionPane.showMessageDialog(null, "Você Venceu :D ", "You Win", JOptionPane.INFORMATION_MESSAGE);
                        novoRound();
                    }
                }  
            }     
        }else{
            JOptionPane.showMessageDialog(null, "Você não pode jogar com 17 pontos ou mais!", "FAULT!", JOptionPane.WARNING_MESSAGE);        
            PlayerStandPerformed(evt);
        } 
        
    }//GEN-LAST:event_PlayerHitPerformed

    private void PlayerStandPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerStandPerformed
        while (!dealer.isStanding()){
            this.CartaAtualDealer = dealer.bet();
            jLabelDealerCount.setText(dealer.getHandTotal().toString());
            
            if (CartaAtualDealer != null){
                DealerHandIcon.setIcon(createImageIcon(CartaAtualDealer.getIconPath()));
                dealerIndexCounter = STACK_INDEX;
            }
        }
        
        if (dealer.getHandTotal() >= 17 && dealer.getHandTotal() <= 21){
            if (dealer.getHandTotal() > jogador.getHandTotal()){
               
                JOptionPane.showMessageDialog(null, "O dealer tinha " +dealer.getHandTotal().toString()+
                        " e Você tinha " +jogador.getHandTotal()+ "\n Você Perdeu :( ", "Game Over", JOptionPane.ERROR_MESSAGE);
                novoRound();
            }else{
                JOptionPane.showMessageDialog(null, "O dealer tinha " +dealer.getHandTotal().toString()+
                        " e Você tinha " +jogador.getHandTotal()+ "\n Você Venceu :D ", "You Win", JOptionPane.INFORMATION_MESSAGE);
                novoRound();
            }
        }else{
            if (dealer.getHandTotal() > 21){
                JOptionPane.showMessageDialog(null, "O dealer tinha " +dealer.getHandTotal().toString()+
                        " e Você tinha " +jogador.getHandTotal()+ "\n Você Venceu :D ", "You Win", JOptionPane.INFORMATION_MESSAGE);
                novoRound();
            }
        }
    }//GEN-LAST:event_PlayerStandPerformed

    //Navegar entre as cartas da mão do jogador.
    private void jButtonPlayerHandLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayerHandLeftActionPerformed
        Stack<Cards> aux;
        aux = jogador.getHand();
        Cards c_prev = CartaAtualPlayer;
        int i_prev = playerIndexCounter;
        javax.swing.Icon I_prev = PlayerHandIcon.getIcon();
        try {
            playerIndexCounter++;
            CartaAtualPlayer = aux.elementAt(aux.size() - (playerIndexCounter +1));
            PlayerHandIcon.setIcon(createImageIcon(CartaAtualPlayer.getIconPath()));
        } catch (ArrayIndexOutOfBoundsException e) {        
            playerIndexCounter = i_prev;
            CartaAtualPlayer = c_prev;
            PlayerHandIcon.setIcon(I_prev);
        }
    }//GEN-LAST:event_jButtonPlayerHandLeftActionPerformed

    private void jButtonPlayerHandRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayerHandRightActionPerformed
        Stack<Cards> aux;
        aux = jogador.getHand();
        Cards c_prev = CartaAtualPlayer;
        int i_prev = playerIndexCounter;
        javax.swing.Icon I_prev = PlayerHandIcon.getIcon();
        try {
            playerIndexCounter--;
            CartaAtualPlayer = aux.elementAt(aux.size() - (playerIndexCounter +1));
            PlayerHandIcon.setIcon(createImageIcon(CartaAtualPlayer.getIconPath()));
        } catch (ArrayIndexOutOfBoundsException e) {        
            playerIndexCounter = i_prev;
            CartaAtualPlayer = c_prev;
            PlayerHandIcon.setIcon(I_prev);
        }
    }//GEN-LAST:event_jButtonPlayerHandRightActionPerformed
    //Navegar entre as cartas da mão do dealer.
    private void jButtonDealerHandLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDealerHandLeftActionPerformed
        Stack<Cards> aux;
        aux = dealer.getHand();
        Cards c_prev = CartaAtualDealer;
        int i_prev = dealerIndexCounter;
        javax.swing.Icon I_prev = DealerHandIcon.getIcon();
        try {
            dealerIndexCounter++;
            CartaAtualDealer = aux.elementAt(aux.size() - (dealerIndexCounter +1));
            DealerHandIcon.setIcon(createImageIcon(CartaAtualDealer.getIconPath()));
        } catch (ArrayIndexOutOfBoundsException e) {
            dealerIndexCounter = i_prev;
            CartaAtualDealer = c_prev;
            DealerHandIcon.setIcon(I_prev);
        }
    }//GEN-LAST:event_jButtonDealerHandLeftActionPerformed

    private void jButtonDealerHandRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDealerHandRightActionPerformed
        Stack<Cards> aux;
        aux = dealer.getHand();
        Cards c_prev = CartaAtualDealer;
        int i_prev = dealerIndexCounter;
        javax.swing.Icon I_prev = DealerHandIcon.getIcon();
        try {
            dealerIndexCounter--;
            CartaAtualDealer = aux.elementAt(aux.size() - (dealerIndexCounter +1));
            DealerHandIcon.setIcon(createImageIcon(CartaAtualDealer.getIconPath()));
        } catch (ArrayIndexOutOfBoundsException e) {
            dealerIndexCounter = i_prev;
            CartaAtualDealer = c_prev;
            DealerHandIcon.setIcon(I_prev);
        }
    }//GEN-LAST:event_jButtonDealerHandRightActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal tp = new TelaPrincipal();
                tp.setVisible(true);
                tp.novoRound();        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DealerHand;
    private javax.swing.JLabel DealerHandIcon;
    private javax.swing.JPanel PlayerHand;
    private javax.swing.JLabel PlayerHandIcon;
    private javax.swing.JButton jButtonDealerHandLeft;
    private javax.swing.JButton jButtonDealerHandRight;
    private javax.swing.JButton jButtonHit;
    private javax.swing.JButton jButtonPlayerHandLeft;
    private javax.swing.JButton jButtonPlayerHandRight;
    private javax.swing.JButton jButtonStand;
    private javax.swing.JLabel jLabelDealerCount;
    private javax.swing.JLabel jLabelDealerTotal;
    private javax.swing.JLabel jLabelPlayerCount;
    private javax.swing.JLabel jLabelPlayerTotal;
    // End of variables declaration//GEN-END:variables

    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        }else {
            System.err.println("Couldn't find file: " + path);
        return null;
        }
    }

}
