/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjackvinteum.view;
//setIcon = jText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackvinteum/view/cards/imagens/10c.png")));

import javax.swing.ImageIcon;

/**
 *
 * @author rodri
 */
public class TelaPrincipal extends javax.swing.JFrame {
       
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
                                            
        initComponents();
        //DealerHandIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/imagens/back.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DealerHand = new javax.swing.JPanel();
        DealerHandIcon = new javax.swing.JLabel();
        PlayerHand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDealerTotal = new javax.swing.JLabel();
        jLabelDealerCount = new javax.swing.JLabel();
        jLabelPlayerTotal = new javax.swing.JLabel();
        jLabelPlayerCount = new javax.swing.JLabel();
        jButtonStand = new javax.swing.JButton();
        jButtonHit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJack Vinte e Um");
        setResizable(false);

        DealerHand.setBackground(new java.awt.Color(214, 217, 223));
        DealerHand.setMaximumSize(new java.awt.Dimension(180, 251));
        DealerHand.setMinimumSize(new java.awt.Dimension(179, 250));
        DealerHand.setPreferredSize(new java.awt.Dimension(179, 250));

        DealerHandIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/imagens/back.png"))); // NOI18N
        DealerHandIcon.setMaximumSize(new java.awt.Dimension(180, 251));

        javax.swing.GroupLayout DealerHandLayout = new javax.swing.GroupLayout(DealerHand);
        DealerHand.setLayout(DealerHandLayout);
        DealerHandLayout.setHorizontalGroup(
            DealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DealerHandIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DealerHandLayout.setVerticalGroup(
            DealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DealerHandIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PlayerHand.setBackground(new java.awt.Color(214, 217, 223));
        PlayerHand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        PlayerHand.setForeground(new java.awt.Color(255, 255, 255));
        PlayerHand.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/imagens/back.png"))); // NOI18N

        javax.swing.GroupLayout PlayerHandLayout = new javax.swing.GroupLayout(PlayerHand);
        PlayerHand.setLayout(PlayerHandLayout);
        PlayerHandLayout.setHorizontalGroup(
            PlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PlayerHandLayout.setVerticalGroup(
            PlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelDealerTotal.setText("DEALER_TOTAL:");

        jLabelDealerCount.setText("0");

        jLabelPlayerTotal.setText("PLAYER_TOTAL:");

        jLabelPlayerCount.setText("0");

        jButtonStand.setText("Stand");

        jButtonHit.setText("Hit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStand)
                    .addComponent(jButtonHit)
                    .addComponent(DealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPlayerTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPlayerCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(PlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDealerTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDealerCount)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDealerTotal)
                                .addComponent(jLabelDealerCount))
                            .addComponent(DealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlayerTotal)
                            .addComponent(jLabelPlayerCount)
                            .addComponent(jButtonStand)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(PlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DealerHand;
    private javax.swing.JLabel DealerHandIcon;
    private javax.swing.JPanel PlayerHand;
    private javax.swing.JButton jButtonHit;
    private javax.swing.JButton jButtonStand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDealerCount;
    private javax.swing.JLabel jLabelDealerTotal;
    private javax.swing.JLabel jLabelPlayerCount;
    private javax.swing.JLabel jLabelPlayerTotal;
    // End of variables declaration//GEN-END:variables

    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        }else {
            System.err.println("Couldn't find file: " + path);
        return null;
        }
    }

}
